---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# timetracker

<!-- badges: start -->
<!-- badges: end -->

The goal of timetracker is to help you work with data from the [GoogleSheets
extension "Time
Tracker"](https://workspace.google.com/marketplace/app/time_tracker/182790105381).

## Installation

You can install the development version of timetracker with:

```r
# install.packages("pak")
pak::pak("maurolepore/timetracker")
```

## TODO Move to R/

```{r}
wrangle <- function(data) {
  raw |> 
    # Wrangle
    clean_names() |>
    # Pick done
    filter(!is.na(start_time), !is.na(stop_time)) |> 
    mutate(difference = make_difftime(stop_time - start_time, units = "hour")) |>
    # Add date
    mutate(date = date(start_time)) |> 
    relocate(date)
}
```

## Example

```{r example}
library(tidyverse)
library(googlesheets4)
library(janitor)
library(timetracker)
```

Read your google sheet with googlesheets4.

```{r}
url <- "https://docs.google.com/spreadsheets/d/1Pz9_Dn24DPpWpEXFggSwZJWSp0DHtYbgpeS1_90KtEA/edit?usp=sharing"
raw <- read_sheet(url)

raw
```

Wrangle the data with the timetracker package.

```{r}
wrangled <- wrangle(raw)

wrangled
```

Analyze the data with the tidyverse.

```{r}
summary <- wrangled |> 
  group_by(case_ref_number) |> 
  summarise(difference = sum(difference))

summary
```

```{r}
ggplot(summary) + 
  geom_col(aes(fct_reorder(case_ref_number, difference), difference))
```

